import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter/foundation.dart';
import 'package:logging/logging.dart';

// Import tables
import 'tables.dart';
import 'daos/card_dao.dart';
import 'daos/todo_schedule_dao.dart';

// Generated by drift_dev when running `dart run build_runner build`
part 'app_database.g.dart';

@DriftDatabase(
  tables: [Tasks, KvStore, AgentActivityMessages, CardCache, SystemActions, TodoScheduleItems, PersonaChatMessages],
  daos: [CardDao, TodoScheduleDao],
)
class AppDatabase extends _$AppDatabase {
  final Logger _logger = Logger('AppDatabase');

  /// Singleton pattern to ensure one DB connection
  static AppDatabase?
      _instance; // We will treat the current opened DB as singleton for the app lifecycle
  static AppDatabase get instance {
    if (_instance == null) {
      throw Exception(
          'Database not initialized. Call AppDatabase.init(userId) first.');
    }
    return _instance!;
  }

  static bool get isInitialized => _instance != null;

  /// Initialize the database for a specific user
  static Future<void> init(String userId) async {
    if (_instance != null) {
      await _instance!.close();
      _instance = null;
    }

    _instance = AppDatabase._(userId);
  }

  /// Private constructor
  AppDatabase._(String userId) : super(_openConnection(userId));

  /// Constructor for testing with a custom executor (e.g., in-memory database)
  @visibleForTesting
  AppDatabase.forTesting(QueryExecutor executor) : super(executor);

  @override
  int get schemaVersion => 10;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (Migrator m) async {
          await m.createAll();
          // Create indices
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_scheduled_at ON tasks(scheduled_at)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_tasks_type_biz_id ON tasks(type, biz_id)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_kv_bucket ON kv_store(bucket)');
          await customStatement(
              'CREATE INDEX IF NOT EXISTS idx_card_cache_timestamp ON card_cache(timestamp)');
        },
        onUpgrade: (Migrator m, int from, int to) async {
          if (from < 2) {
            await m.createTable(agentActivityMessages);
          }
          // Only add agent_id column if upgrading from version 2 to 3
          // If upgrading from version 1, the table was just created with all columns including agent_id
          if (from == 2 && to >= 3) {
            // Try to add the column, but ignore if it already exists
            try {
              await m.addColumn(
                  agentActivityMessages, agentActivityMessages.agentId);
            } catch (e) {
              // If column already exists (duplicate column error), ignore it
              final errorStr = e.toString().toLowerCase();
              if (errorStr.contains('duplicate column') ||
                  (errorStr.contains('sqlite') &&
                      errorStr.contains('agent_id'))) {
                _logger
                    .info('agent_id column already exists, skipping migration');
              } else {
                // Re-throw if it's a different error
                rethrow;
              }
            }
          }
          if (from < 4) {
            try {
              await m.addColumn(tasks, tasks.dependencies);
            } catch (e) {
              _logger.info(
                  'dependencies column might already exist, skipping: $e');
            }
          }
          if (from < 5) {
            await m.createTable(cardCache);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_card_cache_timestamp ON card_cache(timestamp)');
          }
          if (from < 7) {
            await m.createTable(systemActions);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_system_actions_status ON system_actions(status)');
          }
          if (from < 8) {
            try {
              await customStatement(
                  'ALTER TABLE card_cache DROP COLUMN is_draft');
            } catch (e) {
              _logger
                  .info('is_draft column may not exist or already dropped: $e');
            }
          }
          if (from < 9) {
            await m.createTable(personaChatMessages);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_persona_chat_character ON persona_chat_messages(character_id)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_persona_chat_unread ON persona_chat_messages(character_id, is_read)');
          }
          if (from < 10) {
            await m.createTable(todoScheduleItems);
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_todoschedule_status ON todo_schedule_items(status)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_todoschedule_user_status ON todo_schedule_items(user_id, status)');
            await customStatement(
                'CREATE INDEX IF NOT EXISTS idx_todoschedule_due_date ON todo_schedule_items(due_date)');
          }
        },
      );
}

/// Opens the connection using drift_flutter
QueryExecutor _openConnection(String userId) {
  final dbName = 'memex_local_$userId';

  return driftDatabase(name: dbName);
}
