import 'package:memex/utils/date_util.dart';

/// Model representing a schedule aggregation generated by the Schedule Aggregator Agent.
/// This is the structured output consumed by the Magazine Narrative UI.
class ScheduleAggregationModel {
  final String id;
  final DateTime generatedAt;
  final int version;
  final TimeRange timeRange;
  final HeroItem? heroItem;
  final String editorialIntro;
  final List<QuoteBlock> quoteBlocks;
  final List<TimelineDay> timeline;
  final List<CompletedItem> completed;
  final List<Conflict> conflicts;

  ScheduleAggregationModel({
    required this.id,
    required this.generatedAt,
    this.version = 1,
    required this.timeRange,
    this.heroItem,
    this.editorialIntro = '',
    this.quoteBlocks = const [],
    this.timeline = const [],
    this.completed = const [],
    this.conflicts = const [],
  });

  factory ScheduleAggregationModel.fromYaml(Map<String, dynamic> yaml) {
    return ScheduleAggregationModel(
      id: _parseString(yaml['id']),
      generatedAt: _parseDateTime(yaml['generated_at']),
      version: _parseInt(yaml['version']) ?? 1,
      timeRange: TimeRange.fromYaml(
        yaml['time_range'] as Map<String, dynamic>? ?? {},
      ),
      heroItem: yaml['hero_item'] != null
          ? HeroItem.fromYaml(yaml['hero_item'] as Map<String, dynamic>)
          : null,
      editorialIntro: _parseString(yaml['editorial_intro']),
      quoteBlocks: _parseList(yaml['quote_blocks'], QuoteBlock.fromYaml),
      timeline: _parseList(yaml['timeline'], TimelineDay.fromYaml),
      completed: _parseList(yaml['completed'], CompletedItem.fromYaml),
      conflicts: _parseList(yaml['conflicts'], Conflict.fromYaml),
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'generated_at': generatedAt.toIso8601String(),
    'version': version,
    'time_range': timeRange.toJson(),
    if (heroItem != null) 'hero_item': heroItem!.toJson(),
    'editorial_intro': editorialIntro,
    'quote_blocks': quoteBlocks.map((e) => e.toJson()).toList(),
    'timeline': timeline.map((e) => e.toJson()).toList(),
    'completed': completed.map((e) => e.toJson()).toList(),
    'conflicts': conflicts.map((e) => e.toJson()).toList(),
  };

  static DateTime _parseDateTime(dynamic value) {
    return _parseDateTimeNullable(value) ?? DateTime.now();
  }

  static List<T> _parseList<T>(
    dynamic value,
    T Function(Map<String, dynamic>) parser,
  ) {
    if (value == null) return [];
    if (value is! List) return [];
    return value
        .whereType<Map>()
        .map((e) => parser(Map<String, dynamic>.from(e)))
        .toList();
  }
}

class TimeRange {
  final DateTime from;
  final DateTime to;

  TimeRange({required this.from, required this.to});

  factory TimeRange.fromYaml(Map<String, dynamic> yaml) {
    return TimeRange(
      from: _parseDate(yaml['from']),
      to: _parseDate(yaml['to']),
    );
  }

  Map<String, dynamic> toJson() => {
    'from': _formatDate(from),
    'to': _formatDate(to),
  };

  static DateTime _parseDate(dynamic value) {
    if (value == null) return DateTime.now();
    if (value is DateTime) return value;
    if (value is String) return DateTime.tryParse(value) ?? DateTime.now();
    return DateTime.now();
  }

  static String _formatDate(DateTime date) {
    return '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
  }
}

class HeroItem {
  final String cardId;
  final String title;
  final String? description;
  final DateTime? startTime;
  final DateTime? endTime;
  final String? location;
  final int? priority;

  HeroItem({
    required this.cardId,
    required this.title,
    this.description,
    this.startTime,
    this.endTime,
    this.location,
    this.priority,
  });

  factory HeroItem.fromYaml(Map<String, dynamic> yaml) {
    return HeroItem(
      cardId: _parseString(yaml['card_id'], fallback: _parseString(yaml['id'])),
      title: _parseString(yaml['title']),
      description: _parseNullableString(yaml['description']),
      startTime: _parseDateTimeNullable(yaml['start_time']),
      endTime: _parseDateTimeNullable(yaml['end_time']),
      location: _parseNullableString(yaml['location']),
      priority: _parseInt(yaml['priority']),
    );
  }

  Map<String, dynamic> toJson() => {
    'card_id': cardId,
    'title': title,
    if (description != null) 'description': description,
    if (startTime != null) 'start_time': startTime!.toIso8601String(),
    if (endTime != null) 'end_time': endTime!.toIso8601String(),
    if (location != null) 'location': location,
    if (priority != null) 'priority': priority,
  };
}

class QuoteBlock {
  final String title;
  final String content;
  final String priority;
  final String? relatedCardId;

  QuoteBlock({
    required this.title,
    required this.content,
    this.priority = 'normal',
    this.relatedCardId,
  });

  factory QuoteBlock.fromYaml(Map<String, dynamic> yaml) {
    return QuoteBlock(
      title: _parseString(yaml['title']),
      content: _parseString(yaml['content']),
      priority: _parseString(yaml['priority'], fallback: 'normal'),
      relatedCardId: _parseNullableString(yaml['related_card_id']),
    );
  }

  Map<String, dynamic> toJson() => {
    'title': title,
    'content': content,
    'priority': priority,
    if (relatedCardId != null) 'related_card_id': relatedCardId,
  };
}

class TimelineDay {
  final String dayLabel;
  final DateTime? dayDate;
  final List<TimelineItem> items;

  TimelineDay({required this.dayLabel, this.dayDate, this.items = const []});

  factory TimelineDay.fromYaml(Map<String, dynamic> yaml) {
    return TimelineDay(
      dayLabel: _parseString(yaml['day_label']),
      dayDate: _parseDateTimeNullable(yaml['day_date']),
      items: _parseList(yaml['items'], TimelineItem.fromYaml),
    );
  }

  Map<String, dynamic> toJson() => {
    'day_label': dayLabel,
    if (dayDate != null) 'day_date': _formatDate(dayDate!),
    'items': items.map((e) => e.toJson()).toList(),
  };

  static String _formatDate(DateTime date) {
    return '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
  }
}

class TimelineItem {
  final String cardId;
  final String title;
  final String status;
  final DateTime? startTime;
  final String type;
  final int? priority;
  final String? description;
  final List<ScheduleSubtask> subtasks;

  TimelineItem({
    required this.cardId,
    required this.title,
    this.status = 'pending',
    this.startTime,
    this.type = 'event',
    this.priority,
    this.description,
    this.subtasks = const [],
  });

  factory TimelineItem.fromYaml(Map<String, dynamic> yaml) {
    return TimelineItem(
      cardId: _parseString(yaml['card_id'], fallback: _parseString(yaml['id'])),
      title: _parseString(yaml['title']),
      status: _parseString(yaml['status'], fallback: 'pending'),
      startTime: _parseDateTimeNullable(yaml['start_time']),
      type: _parseString(yaml['type'], fallback: 'event'),
      priority: _parseInt(yaml['priority']),
      description: _parseNullableString(yaml['description']),
      subtasks: _parseList(
        yaml['subtasks'],
        ScheduleSubtask.fromYaml,
      ).where((subtask) => subtask.title.trim().isNotEmpty).toList(),
    );
  }

  Map<String, dynamic> toJson() => {
    'card_id': cardId,
    'title': title,
    'status': status,
    if (startTime != null) 'start_time': startTime!.toIso8601String(),
    'type': type,
    if (priority != null) 'priority': priority,
    if (description != null) 'description': description,
    if (subtasks.isNotEmpty)
      'subtasks': subtasks.map((e) => e.toJson()).toList(),
  };
}

class ScheduleSubtask {
  final String title;
  final bool completed;

  const ScheduleSubtask({required this.title, this.completed = false});

  factory ScheduleSubtask.fromYaml(Map<String, dynamic> yaml) {
    return ScheduleSubtask(
      title: _parseString(yaml['title']),
      completed: _parseBool(yaml['completed']) ?? false,
    );
  }

  ScheduleSubtask copyWith({String? title, bool? completed}) {
    return ScheduleSubtask(
      title: title ?? this.title,
      completed: completed ?? this.completed,
    );
  }

  Map<String, dynamic> toJson() => {'title': title, 'completed': completed};
}

class CompletedItem {
  final String cardId;
  final String title;
  final DateTime? completedAt;

  CompletedItem({required this.cardId, required this.title, this.completedAt});

  factory CompletedItem.fromYaml(Map<String, dynamic> yaml) {
    return CompletedItem(
      cardId: _parseString(yaml['card_id'], fallback: _parseString(yaml['id'])),
      title: _parseString(yaml['title']),
      completedAt: _parseDateTimeNullable(yaml['completed_at']),
    );
  }

  Map<String, dynamic> toJson() => {
    'card_id': cardId,
    'title': title,
    if (completedAt != null) 'completed_at': completedAt!.toIso8601String(),
  };
}

class Conflict {
  final String description;
  final List<String> itemIds;

  Conflict({required this.description, this.itemIds = const []});

  factory Conflict.fromYaml(Map<String, dynamic> yaml) {
    return Conflict(
      description: _parseString(yaml['description']),
      itemIds:
          (yaml['item_ids'] as List?)
              ?.map((item) => item.toString())
              .toList() ??
          [],
    );
  }

  Map<String, dynamic> toJson() => {
    'description': description,
    'item_ids': itemIds,
  };
}

DateTime? _parseDateTimeNullable(dynamic value) {
  return parseLocalDateTime(value);
}

List<T> _parseList<T>(dynamic value, T Function(Map<String, dynamic>) parser) {
  if (value == null) return [];
  if (value is! List) return [];
  return value
      .whereType<Map>()
      .map((e) => parser(Map<String, dynamic>.from(e)))
      .toList();
}

String _parseString(dynamic value, {String fallback = ''}) {
  if (value == null) return fallback;
  if (value is String) return value;
  return value.toString();
}

String? _parseNullableString(dynamic value) {
  if (value == null) return null;
  if (value is String) return value;
  return value.toString();
}

int? _parseInt(dynamic value) {
  if (value == null) return null;
  if (value is int) return value;
  if (value is num) return value.toInt();
  if (value is String) {
    final parsed = int.tryParse(value);
    if (parsed != null) return parsed;
    return switch (value.toLowerCase().trim()) {
      'high' || 'urgent' || '重要' || '高' => 3,
      'medium' || 'normal' || '中' => 2,
      'low' || '低' => 1,
      _ => null,
    };
  }
  return null;
}

bool? _parseBool(dynamic value) {
  if (value == null) return null;
  if (value is bool) return value;
  if (value is num) return value != 0;
  if (value is String) {
    return switch (value.toLowerCase().trim()) {
      'true' || 'yes' || 'y' || '1' || 'done' || 'completed' => true,
      'false' || 'no' || 'n' || '0' || 'pending' || 'todo' => false,
      _ => null,
    };
  }
  return null;
}
